### ISSUE TITLE
Updating a translation in a child language can override the parent language translation

### ISSUE THREAD

**Issue by rjnl** [andrewhancox/moodle-filter_translations#98]
Consider the following scenario:

Translate some content in a parent language pack, eg: "fr".
Then switch language to "fr_ca". You should see the content translation inherited from the parent lang pack, "fr".
If you wish to edit this translation, the Edit translation form loads with language set to "fr". 

If you edit the translation and save changes with language set to "fr", then the original translation for "fr" is updated.
If you edit the translation and save changes with language set to "fr_ca", then the original translation for "fr" is "lost". When you change the lang back to "fr" you will now see "Missing translation" for the content that was earlier translated.

Perhaps we should save such translations as a new entry, rather then updating it???

**Comment by jgramp** [comment]
If your language is set to fr_ca this is what should load in the form,
regardless of text editor being pre-loaded with fr content (because fr_ca
content doesn't exist). basically the logic should be:
1. Check the language of the user.
2. Check if a translation exists in this language (fr_ca). Or if it's a
*_wp language we check for the parent (without the _wp).
3. If no fr_ca translation exists check and load the parent language
translation (fr).
4. If no parent language translation exists load the original (English)
language content.

In all of these cases, the language within the editor, which is saved when
the translation us saved remain fr_ca. Because that is the language the
user has set in the Moodle top nav bar.

Nothing should be getting lost in the process of saving child language
variants. And child language variants shouldn't be updating the parent
language.

**Comment by rjnl** [comment]
@andrewhancox - I've created a fix for this issue.
https://github.com/rjnl/moodle-filter_translations/commit/b9b59f3ab91e3811c1711eabb32d1361e9b07155

**Comment by rjnl** [comment]
Fix merged.
